# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: perform_comment_action_params.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'perform_comment_action_params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#perform_comment_action_params.proto\"\xc3\x01\n\x1aPerformCommentActionParams\x12\x0e\n\x06\x61\x63tion\x18\x01 \x02(\x05\x12\x0c\n\x04int1\x18\x02 \x02(\x05\x12\x12\n\ncomment_id\x18\x03 \x02(\t\x12\x0c\n\x04int2\x18\x06 \x02(\x05\x12\x16\n\x0e\x61\x63tion_variant\x18\x07 \x01(\x05\x12\x0c\n\x04int3\x18\x15 \x02(\x05\x12\x0f\n\x07post_id\x18\x16 \x02(\t\x12\x12\n\nchannel_id\x18\x17 \x02(\t\x12\x0c\n\x04int4\x18\x1e \x02(\x05\x12\x0c\n\x04int5\x18/ \x02(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perform_comment_action_params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERFORMCOMMENTACTIONPARAMS']._serialized_start=40
  _globals['_PERFORMCOMMENTACTIONPARAMS']._serialized_end=235
# @@protoc_insertion_point(module_scope)
