# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fixed_comment_params.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fixed_comment_params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66ixed_comment_params.proto\"z\n\x12\x46ixedCommentParams\x12)\n\x04msg1\x18\x9c\xd5\xa0& \x02(\x0b\x32\x18.FixedCommentParams.Msg1\x1a\x39\n\x04Msg1\x12\x0c\n\x04str1\x18\x02 \x02(\t\x12#\n\x1bInnerFixedCommentParams_b64\x18\x03 \x02(\t\"\xf7\x02\n\x17InnerFixedCommentParams\x12\x0c\n\x04str2\x18\x02 \x02(\t\x12+\n\x04msg2\x18\x35 \x02(\x0b\x32\x1d.InnerFixedCommentParams.Msg2\x12+\n\x04msg3\x18\x38 \x02(\x0b\x32\x1d.InnerFixedCommentParams.Msg3\x1a\x41\n\x04Msg2\x12+\n\x04msg4\x18\x04 \x02(\x0b\x32\x1d.InnerFixedCommentParams.Msg4\x12\x0c\n\x04str3\x18\x08 \x02(\t\x1a[\n\x04Msg4\x12\x0c\n\x04int1\x18\x06 \x02(\x05\x12\x12\n\ncomment_id\x18\x10 \x01(\t\x12\x0c\n\x04int2\x18\x1b \x02(\x05\x12\x0f\n\x07post_id\x18\x1d \x02(\t\x12\x12\n\nchannel_id\x18\x1e \x02(\t\x1aT\n\x04Msg3\x12\x12\n\nchannel_id\x18\x02 \x02(\t\x12\x0f\n\x07post_id\x18\x03 \x02(\t\x12\x12\n\ncomment_id\x18\x08 \x01(\t\x12\x13\n\x0b\x63hannel_id2\x18\x0b \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fixed_comment_params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIXEDCOMMENTPARAMS']._serialized_start=30
  _globals['_FIXEDCOMMENTPARAMS']._serialized_end=152
  _globals['_FIXEDCOMMENTPARAMS_MSG1']._serialized_start=95
  _globals['_FIXEDCOMMENTPARAMS_MSG1']._serialized_end=152
  _globals['_INNERFIXEDCOMMENTPARAMS']._serialized_start=155
  _globals['_INNERFIXEDCOMMENTPARAMS']._serialized_end=530
  _globals['_INNERFIXEDCOMMENTPARAMS_MSG2']._serialized_start=286
  _globals['_INNERFIXEDCOMMENTPARAMS_MSG2']._serialized_end=351
  _globals['_INNERFIXEDCOMMENTPARAMS_MSG4']._serialized_start=353
  _globals['_INNERFIXEDCOMMENTPARAMS_MSG4']._serialized_end=444
  _globals['_INNERFIXEDCOMMENTPARAMS_MSG3']._serialized_start=446
  _globals['_INNERFIXEDCOMMENTPARAMS_MSG3']._serialized_end=530
# @@protoc_insertion_point(module_scope)
