# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: update_comment_params.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'update_comment_params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bupdate_comment_params.proto\"\xa9\x01\n\x13UpdateCommentParams\x12\x12\n\ncomment_id\x18\x01 \x02(\t\x12\'\n\x04msg1\x18\x05 \x02(\x0b\x32\x19.UpdateCommentParams.Msg1\x12\x0c\n\x04int2\x18\x08 \x02(\x05\x12\x0f\n\x07post_id\x18\n \x02(\t\x12\x12\n\nchannel_id\x18\x0b \x02(\t\x12\x0c\n\x04str1\x18\x12 \x02(\t\x1a\x14\n\x04Msg1\x12\x0c\n\x04int1\x18\x01 \x02(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'update_comment_params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATECOMMENTPARAMS']._serialized_start=32
  _globals['_UPDATECOMMENTPARAMS']._serialized_end=201
  _globals['_UPDATECOMMENTPARAMS_MSG1']._serialized_start=181
  _globals['_UPDATECOMMENTPARAMS_MSG1']._serialized_end=201
# @@protoc_insertion_point(module_scope)
