# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: create_comment_params.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'create_comment_params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63reate_comment_params.proto\"\x95\x01\n\x13\x43reateCommentParams\x12\'\n\x04msg1\x18\x05 \x02(\x0b\x32\x19.CreateCommentParams.Msg1\x12\x0c\n\x04int2\x18\n \x02(\x05\x12\x0f\n\x07post_id\x18\x14 \x02(\t\x12\x12\n\nchannel_id\x18\x15 \x02(\t\x12\x0c\n\x04int3\x18- \x02(\x05\x1a\x14\n\x04Msg1\x12\x0c\n\x04int1\x18\x01 \x02(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'create_comment_params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECOMMENTPARAMS']._serialized_start=32
  _globals['_CREATECOMMENTPARAMS']._serialized_end=181
  _globals['_CREATECOMMENTPARAMS_MSG1']._serialized_start=161
  _globals['_CREATECOMMENTPARAMS_MSG1']._serialized_end=181
# @@protoc_insertion_point(module_scope)
