# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comment_replies_params.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'comment_replies_params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63omment_replies_params.proto\"\x80\x01\n\x14\x43ommentRepliesParams\x12+\n\x04msg1\x18\x9c\xd5\xa0& \x02(\x0b\x32\x1a.CommentRepliesParams.Msg1\x1a;\n\x04Msg1\x12\x0c\n\x04str2\x18\x02 \x02(\t\x12%\n\x1dInnerCommentRepliesParams_b64\x18\x03 \x02(\t\"\xb0\x04\n\x19InnerCommentRepliesParams\x12\x0c\n\x04str2\x18\x02 \x02(\t\x12-\n\x04msg2\x18\x19 \x02(\x0b\x32\x1f.InnerCommentRepliesParams.Msg2\x12-\n\x04msg3\x18- \x02(\x0b\x32\x1f.InnerCommentRepliesParams.Msg3\x12-\n\x04msg4\x18\x35 \x02(\x0b\x32\x1f.InnerCommentRepliesParams.Msg4\x1a\x17\n\x04Msg2\x12\x0f\n\x07post_id\x18\x16 \x02(\t\x1a\"\n\x04Msg3\x12\x0c\n\x04int2\x18\x02 \x02(\x05\x12\x0c\n\x04int3\x18\x03 \x02(\x05\x1aS\n\x04Msg4\x12-\n\x04msg5\x18\x03 \x02(\x0b\x32\x1f.InnerCommentRepliesParams.Msg5\x12\x1c\n\x14\x63omment_replies_item\x18\x08 \x02(\t\x1a\xb9\x01\n\x04Msg5\x12\x12\n\ncomment_id\x18\x02 \x02(\t\x12-\n\x04msg6\x18\x04 \x02(\x0b\x32\x1f.InnerCommentRepliesParams.Msg6\x12\x12\n\nchannel_id\x18\x05 \x02(\t\x12\x0c\n\x04int8\x18\x08 \x02(\x05\x12\x0c\n\x04int9\x18\t \x02(\x05\x12\x0f\n\x07post_id\x18\x0f \x02(\t\x12-\n\x04msg7\x18\x10 \x02(\x0b\x32\x1f.InnerCommentRepliesParams.Msg7\x1a\x14\n\x04Msg6\x12\x0c\n\x04int1\x18\x01 \x02(\x05\x1a\x14\n\x04Msg7\x12\x0c\n\x04int1\x18\x01 \x02(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comment_replies_params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMENTREPLIESPARAMS']._serialized_start=33
  _globals['_COMMENTREPLIESPARAMS']._serialized_end=161
  _globals['_COMMENTREPLIESPARAMS_MSG1']._serialized_start=102
  _globals['_COMMENTREPLIESPARAMS_MSG1']._serialized_end=161
  _globals['_INNERCOMMENTREPLIESPARAMS']._serialized_start=164
  _globals['_INNERCOMMENTREPLIESPARAMS']._serialized_end=724
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG2']._serialized_start=348
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG2']._serialized_end=371
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG3']._serialized_start=373
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG3']._serialized_end=407
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG4']._serialized_start=409
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG4']._serialized_end=492
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG5']._serialized_start=495
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG5']._serialized_end=680
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG6']._serialized_start=682
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG6']._serialized_end=702
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG7']._serialized_start=704
  _globals['_INNERCOMMENTREPLIESPARAMS_MSG7']._serialized_end=724
# @@protoc_insertion_point(module_scope)
